name: roomfinder
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1
environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter
  geolocator: ^14.0.0
  cupertino_icons: ^1.0.8
  http: ^1.3.0
  image_picker: ^1.1.2
  provider: ^6.1.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.14.3

flutter:
  uses-material-design: true
  assets:
    - assets/logo.png
    - assets/logo_dark.png
    - assets/app_icon.png
    - assets/calendar.png
    - assets/guest.png
    - assets/heart.png
    - assets/house1.png
    - assets/lupa.png
    - assets/user.png


flutter_icons:
  ios: true
  remove_alpha_ios: true
  image_path: "assets/app_icon.png"