name: roomfinder
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1
environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter
  geolocator: ^14.0.0 # for location services
  cupertino_icons: ^1.0.8 # for iOS icons
  http: ^1.3.0 # for API calls
  image_picker: ^1.1.2 # for picking images
  provider: ^6.1.5 # contrast / big text
  intl: ^0.20.2 # for date formatting
  flutter_adaptive_scaffold: ^0.3.3 # for adaptive navigation
  image: ^4.1.7 # for image manipulation
  flutter_image_compress: ^2.2.0 # for image compression
  path: ^1.9.0 # for file path manipulation
  http_parser: ^4.0.0 # for parsing HTTP responses
  socket_io_client: ^3.1.2 # for real-time communication
  firebase_core: ^2.32.0 # for Firebase initialization
  firebase_messaging: ^14.7.10 # for push notifications
  flutter_local_notifications: ^19.1.0 # nice foreground banners
  cached_network_image: ^3.2.3 # for caching network images
  connectivity_plus: ^6.0.1 # for checking network connectivity
  hive: ^2.2.3 # for local storage
  hive_flutter: ^1.1.0 # for Flutter integration with Hive
  path_provider: ^2.1.3 # for finding commonly used locations on the filesystem

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.14.3
  hive_generator: ^2.0.1
  build_runner: ^2.4.8

flutter:
  uses-material-design: true
  assets:
    - assets/logo.png
    - assets/logo_dark.png
    - assets/app_icon.png
    - assets/calendar.png
    - assets/guest.png
    - assets/heart.png
    - assets/house1.png
    - assets/lupa.png
    - assets/user.png


flutter_icons:
  ios: true
  remove_alpha_ios: true
  image_path: "assets/app_icon.png"